name: Automated API tests using Postman CLI
on: push
jobs:
  automated-api-tests:
    runs-on: ubuntu-latest  # Переключаемся на ubuntu для лучшей поддержки Docker
    steps:
      - uses: actions/checkout@v4
      
      # Установка Docker Compose
      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose-plugin
          docker compose version
        
      # Сборка и запуск контейнеров
      - name: Build and start containers
        run: |
          docker compose up -d
          
      # Ожидание запуска сервера
      - name: Wait for server
        run: |
          for i in {1..30}; do
            if curl -s http://localhost:8081 > /dev/null; then
              echo "Server is up!"
              exit 0
            fi
            echo "Waiting for server... ($i/30)"
            sleep 2
          done
          echo "Server did not come up within 60 seconds"
          exit 1
          
      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
          
      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}
        
      - name: Run API tests
        run: |
          postman collection run "14149783-59d8999f-8e0e-4cfd-af67-728af5d11353" -e "14149783-64297a7d-7072-4d30-af58-505ddfa96ee9"
        
      # Остановка контейнеров после тестов
      - name: Stop containers
        if: always()  # Выполняется даже если предыдущие шаги завершились с ошибкой
        run: docker compose down
